import { HistoricalEvent } from "./Components/MapsApp";

const eventsData: HistoricalEvent[] = [
  {
    id: 1,
    title: "152 Alexander St, Princeton, NJ 08540",
    description: "💑 A charming spot in Princeton, New Jersey - perfect for a romantic stroll.",
    position: [40.349274, -74.653627],
    category: "Dates",
  },
  {
    id: 2,
    title: "GU, 579 Broadway, New York, NY 10012",
    description: "🛍️ Explore the trendy GU store in the heart of New York, NY - a shopping date awaits! 🛒",
    position: [40.724130, -73.997205],
    category: "Dates",
  },
  {
    id: 3,
    title: "Levain Bakery – Upper East Side, NYC, 3rd Avenue, New York, NY",
    description: "🍪 Indulge in sweet moments at Levain Bakery in Upper East Side, New York, NY. 🍰",
    position: [40.773503, -73.960212],
    category: "Dates",
  },
  {
    id: 4,
    title: "UNIQLO Soho Store, 546 Broadway, New York, NY 10012",
    description: "👗 Fashion-forward date at UNIQLO Soho store in New York, NY. Find the perfect outfit! 👔",
    position: [40.725697, -73.998438],
    category: "Dates",
  },
  {
    id: 5,
    title: "MUJI SOHO, 455 Broadway, New York, NY 10013",
    description: "🎨 Explore the minimalist charm of MUJI SOHO in New York, NY - a date for the creative souls! 🖌️",
    position: [40.720131, -74.000279],
    category: "Dates",
  },
  {
    id: 6,
    title: "North Dumpling, 27A Essex St, New York, NY 10002",
    description: "🌃 A romantic night out in the vibrant city of New York, NY - North Dumpling is the place to be! 🌙",
    position: [40.715167, -73.991241],
    category: "Dates",
  },
  {
    id: 7,
    title: "558 Broadway, New York, NY 10012",
    description: "🌆 Exciting date night at 558 Broadway in New York, NY - where the city lights meet love! 💖",
    position: [40.724415, -73.999232],
    category: "Dates",
  },
  {
    id: 8,
    title: "53 Bayard St., Chinatown",
    description: "🏮 Wander through the enchanting streets of Chinatown, New York, NY - a date filled with culture and charm! 🥢",
    position: [40.715090, -73.996156],
    category: "Dates",
  },
  {
    id: 9,
    title: "Pier 35, FDR Dr, New York, NY 10002",
    description: "🌊 A romantic waterfront date on FDR Drive in New York, NY - Pier 35 awaits with breathtaking views! 🌅",
    position: [40.710181, -73.973605],
    category: "Dates",
  },
  {
    id: 10,
    title: "Pier 35, FDR Dr, New York, NY 10002",
    description: "🌊 Another romantic waterfront date on FDR Drive in New York, NY - Pier 35 offers love by the water! 💑",
    position: [40.710181, -73.973605],
    category: "Dates",
  },
  {
    id: 11,
    title: "Bryant Park, New York, NY 10018",
    description: "🌳 Escape to the beautiful Bryant Park in New York, NY - a serene and romantic spot in the heart of the city! 🍃",
    position: [40.753596, -73.984527],
    category: "Dates",
  },
  {
    id: 12,
    title: "Photofolio: 11 W 32nd St, New York, NY 10001",
    description: "📸 Capture romantic memories at Photofolio on West 32nd St, New York, NY - a date filled with snapshots of love! ❤️",
    position: [40.747032, -73.987377],
    category: "Dates",
  },
  {
    id: 13,
    title: "Bryant Park, New York, NY 10018",
    description: "🌳 Another romantic rendezvous at Bryant Park in New York, NY - where love blooms in the heart of the city! 💕",
    position: [40.753596, -73.984527],
    category: "Dates",
  },
  {
    id: 14,
    title: "152 Alexander St, Princeton, NJ 08540",
    description: "💑 Charming spot in Princeton, NJ - perfect for a romantic stroll.",
    position: [40.349274, -74.653627],
    category: "Dates",
  },
  {
    id: 15,
    title: "Princeton Junction",
    description: "🚉 Quaint location near Princeton Junction - a charming escape for a romantic getaway! 🌟",
    position: [40.3100, -74.5917],
    category: "Dates",
  },
  {
    id: 16,
    title: "3601 Walnut St, Philadelphia, PA 19104",
    description: "🌆 Explore the vibrant streets of Philadelphia, PA - a perfect setting for a romantic adventure! 💖",
    position: [39.9530, -75.1893],
    category: "Dates",
  },
  {
    id: 17,
    title: "Penn/City",
    description: "🏙️ City vibes at Penn/City in Philadelphia, PA - where love meets the urban landscape! 🌃",
    position: [39.9549, -75.1817],
    category: "Dates",
  },
  {
    id: 18,
    title: "1400 John F Kennedy Blvd, Philadelphia, PA 19107",
    description: "🏰 Romantic moments await at 1400 John F Kennedy Blvd, Philadelphia, PA - a love story in the heart of the city! ❤️",
    position: [39.9546, -75.1651],
    category: "Dates",
  },
  {
    id: 19,
    title: "1001 Market St APT 3010, Philadelphia, PA 19107",
    description: "🌇 Elevate your date night at 1001 Market St APT 3010, Philadelphia, PA - a cozy nest in the city lights! 🌟",
    position: [39.9526, -75.1586],
    category: "Dates",
  },
  {
    id: 20,
    title: "Terakawa Ramen, 204 N 9th St, Philadelphia, PA 19107",
    description: "🍜 Savor the flavors of love at Terakawa Ramen in Philadelphia, PA - a noodle date to remember! 🥢",
    position: [39.9584, -75.1537],
    category: "Dates",
  },
  {
    id: 21,
    title: "780 S 2nd St, Philadelphia, PA 19147",
    description: "🌆 Romantic vibes at 780 S 2nd St, Philadelphia, PA - where the streets whisper tales of love! 💕",
    position: [39.9414, -75.1456],
    category: "Dates",
  },
  {
    id: 22,
    title: "1326 Spruce St, Philadelphia, PA 19107",
    description: "🏡 Discover hidden romance at 1326 Spruce St, Philadelphia, PA - a charming address for lovebirds! 🌹",
    position: [39.9472, -75.1616],
    category: "Dates",
  },
  {
    id: 23,
    title: "Lanzhou hand-pulled noodles, 935 Arch St, Philadelphia, PA 19107",
    description: "🍜 Dive into a bowl of love at Lanzhou Hand-Pulled Noodles in Philadelphia, PA - a noodle date for two! 🥢",
    position: [39.9536, -75.1572],
    category: "Dates",
  },
  {
    id: 24,
    title: "Momofuku Noodle Bar, 171 1st Avenue, New York, NY 10003",
    description: "🍜 Dive into the world of savory noodles at Momofuku Noodle Bar in New York, NY - a haven for noodle lovers! 🥢",
    position: [40.7294, -73.9841],
    category: "Food",
  },
  {
    id: 25,
    title: "Joe's Shanghai, 9 Pell St, New York, NY 10013",
    description: "🥟 Savor the taste of authentic soup dumplings at Joe's Shanghai in New York, NY - a dumpling paradise! 🍲",
    position: [40.7149, -73.9977],
    category: "Food",
  },
  {
    id: 26,
    title: "Xi'an Famous Foods, 81 St. Marks Pl, New York, NY 10003",
    description: "🌶️ Spice up your date with flavors from Xi'an Famous Foods in New York, NY - a journey through bold and delicious cuisine! 🍜",
    position: [40.7291, -73.9863],
    category: "Food",
  },
  {
    id: 27,
    title: "Han Dynasty, 90 3rd Ave, New York, NY 10003",
    description: "🌶️ Satisfy your spice cravings at Han Dynasty in New York, NY - where bold flavors meet a cozy atmosphere! 🍛",
    position: [40.7317, -73.9886],
    category: "Food",
  },
  {
    id: 28,
    title: "Dim Sum Garden, 1020 Race St, Philadelphia, PA 19107",
    description: "🥢 Discover the art of dim sum at Dim Sum Garden in Philadelphia, PA - a feast of flavors and dumplings await! 🍤",
    position: [39.9524, -75.1598],
    category: "Food",
  },
  {
    id: 29,
    title: "Tuna Bar, 205 Race St, Philadelphia, PA 19106",
    description: "🍣 Indulge in a seafood delight at Tuna Bar in Philadelphia, PA - where fresh sushi meets an elegant dining experience! 🌊",
    position: [39.9532, -75.1431],
    category: "Food",
  },
  {
    id: 30,
    title: "Pho Xe Lua, 907 Race St, Philadelphia, PA 19107",
    description: "🍜 Warm your soul with a bowl of pho at Pho Xe Lua in Philadelphia, PA - a Vietnamese delight in the heart of the city! 🍲",
    position: [39.9529, -75.1553],
    category: "Food",
  },
  {
    id: 31,
    title: "Sakura Mandarin, 1038 Race St, Philadelphia, PA 19107",
    description: "🌸 Embark on a culinary journey at Sakura Mandarin in Philadelphia, PA - where the art of Chinese cuisine meets a romantic setting! 🥢",
    position: [39.9538, -75.1563],
    category: "Food",
  },
  {
    id: 32,
    title: "Central Park, New York, NY 10022",
    description: "🌳 Escape to the enchanting Central Park in New York, NY - a green oasis with endless entertainment possibilities! 🚴‍♂️🎭",
    position: [40.7851, -73.9683],
    category: "Entertainment",
  },
  {
    id: 33,
    title: "Broadway Theatre District, New York, NY 10036",
    description: "🎭 Immerse yourself in the magic of Broadway in New York, NY - where world-class performances and entertainment come to life! 🌟",
    position: [40.7589, -73.9851],
    category: "Entertainment",
  },
  {
    id: 34,
    title: "Top of the Rock Observation Deck, 30 Rockefeller Plaza, New York, NY 10112",
    description: "🏙️ Elevate your date night at the Top of the Rock Observation Deck in New York, NY - panoramic views and romantic moments await! 🌆",
    position: [40.7591, -73.9794],
    category: "Entertainment",
  },
  {
    id: 35,
    title: "The Metropolitan Museum of Art, 1000 5th Ave, New York, NY 10028",
    description: "🎨 Explore the art world at The Met in New York, NY - a cultural date filled with creativity and inspiration! 🖼️",
    position: [40.7794, -73.9632],
    category: "Entertainment",
  },
  {
    id: 36,
    title: "Philadelphia Museum of Art, 2600 Benjamin Franklin Pkwy, Philadelphia, PA 19130",
    description: "🏛️ Dive into the world of art at the Philadelphia Museum of Art - a cultural haven in the heart of the city! 🎨",
    position: [39.9652, -75.1806],
    category: "Entertainment",
  },
  {
    id: 37,
    title: "Liberty Bell, 526 Market St, Philadelphia, PA 19106",
    description: "🔔 Discover the historic Liberty Bell in Philadelphia, PA - a symbol of freedom and a perfect spot for a date filled with history! 🇺🇸",
    position: [39.9496, -75.1502],
    category: "Entertainment",
  },
  {
    id: 38,
    title: "Spruce Street Harbor Park, 301 S Christopher Columbus Blvd, Philadelphia, PA 19106",
    description: "⛵ Enjoy a romantic evening at Spruce Street Harbor Park in Philadelphia, PA - where lights, water, and love create the perfect ambiance! 🌌",
    position: [39.9471, -75.1404],
    category: "Entertainment",
  },
  {
    id: 39,
    title: "The Franklin Institute, 222 N 20th St, Philadelphia, PA 19103",
    description: "🔬 Embark on a journey of discovery at The Franklin Institute in Philadelphia, PA - a fun and interactive date for science enthusiasts! 🌌",
    position: [39.9565, -75.1722],
    category: "Entertainment",
  },
  {
    id: 40,
    title: "Spot Dessert Bar, 13 St Marks Pl, New York, NY 10003",
    description: "🍰 Indulge in sweet creations at Spot Dessert Bar in New York, NY - a dessert haven with Asian-inspired delights! 🍨🍵",
    position: [40.7291, -73.9894],
    category: "Desserts",
  },
  {
    id: 41,
    title: "Taiyaki NYC, 119 Baxter St, New York, NY 10013",
    description: "🐟 Satisfy your sweet tooth with Taiyaki NYC in New York, NY - where fish-shaped cones meet delicious soft-serve and toppings! 🍦🍬",
    position: [40.7183, -73.9991],
    category: "Desserts",
  },
  {
    id: 42,
    title: "Tous Les Jours, 31 W 32nd St, New York, NY 10001",
    description: "🥐 Experience the delight of pastries and desserts at Tous Les Jours in New York, NY - a taste of sweet elegance! 🍰🍮",
    position: [40.7472, -73.9875],
    category: "Desserts",
  },
  {
    id: 43,
    title: "Vivi Bubble Tea, 49 Bayard St, New York, NY 10013",
    description: "🍵 Quench your thirst and sweet cravings at Vivi Bubble Tea in New York, NY - where bubble tea meets a world of flavors! 🥤🍭",
    position: [40.7150, -73.9973],
    category: "Desserts",
  },
  {
    id: 44,
    title: "Teassert Bar, 111 N 10th St, Philadelphia, PA 19107",
    description: "🍵 Dive into a world of tea-infused desserts at Teassert Bar in Philadelphia, PA - where flavors blossom in every bite! 🌸🍰",
    position: [39.9569, -75.1557],
    category: "Desserts",
  },
  {
    id: 45,
    title: "Yagi Desserts, 1006 Arch St, Philadelphia, PA 19107",
    description: "🍨 Sweeten your date with delightful desserts at Yagi Desserts in Philadelphia, PA - a haven for lovers of Asian sweets! 🍡🍧",
    position: [39.9537, -75.1587],
    category: "Desserts",
  },
  {
    id: 46,
    title: "Honeygrow, 1601 Sansom St, Philadelphia, PA 19103",
    description: "🍯 Treat yourself to honey-infused desserts at Honeygrow in Philadelphia, PA - a unique and delicious experience awaits! 🍦🍯",
    position: [39.9527, -75.1662],
    category: "Desserts",
  },
  {
    id: 47,
    title: "Snow Garden, 1016 Race St, Philadelphia, PA 19107",
    description: "❄️ Experience the joy of snowflake desserts at Snow Garden in Philadelphia, PA - a cool and sweet escape for your date! 🍨❄️",
    position: [39.9532, -75.1559],
    category: "Desserts",
  },
  {
    id: 48,
    title: "Aspen Mountain Ski Resort, Aspen, CO 81611",
    description: "⛷️ Hit the slopes and enjoy luxury lodging at Aspen Mountain Ski Resort in Aspen, CO - a winter wonderland for skiing enthusiasts! 🏔️❄️",
    position: [39.1878, -106.8184],
    category: "Entertainment",
  },
  {
    id: 49,
    title: "Park City Mountain Resort, Park City, UT 84060",
    description: "🏂 Experience thrilling snowboarding and cozy lodges at Park City Mountain Resort in Park City, UT - a snowy paradise for winter fun! 🏔️❄️",
    position: [40.6461, -111.4980],
    category: "Entertainment",
  },
  {
    id: 50,
    title: "Stowe Mountain Resort, Stowe, VT 05672",
    description: "⛷️ Ski through scenic landscapes and unwind in charming lodges at Stowe Mountain Resort in Stowe, VT - a picturesque retreat for snow lovers! 🏔️❄️",
    position: [44.5289, -72.7963],
    category: "Entertainment",
  },
  {
    id: 51,
    title: "Jackson Hole Mountain Resort, Teton Village, WY 83025",
    description: "🏂 Conquer the slopes and enjoy rustic lodges at Jackson Hole Mountain Resort in Teton Village, WY - an adventure-filled winter getaway! 🏔️❄️",
    position: [43.5878, -110.8276],
    category: "Entertainment",
  },
  {
    id: 52,
    title: "Breckenridge Ski Resort, Breckenridge, CO 80424",
    description: "⛷️ Discover the joy of skiing and unwind in cozy lodges at Breckenridge Ski Resort in Breckenridge, CO - a snowy haven for winter sports! 🏔️❄️",
    position: [39.4806, -106.0664],
    category: "Entertainment",
  },
  {
    id: 53,
    title: "Lake Tahoe Ski Resorts, South Lake Tahoe, CA 96150",
    description: "🏂 Enjoy the thrill of snowboarding and lakeside lodging at Lake Tahoe Ski Resorts in South Lake Tahoe, CA - where adventure meets serenity! 🏔️❄️",
    position: [38.9399, -119.9772],
    category: "Entertainment",
  },
  {
    id: 54,
    title: "Killington Ski Resort, Killington, VT 05751",
    description: "⛷️ Ski on challenging terrains and relax in comfortable lodges at Killington Ski Resort in Killington, VT - an exhilarating winter escape! 🏔️❄️",
    position: [43.6772, -72.7794],
    category: "Entertainment",
  },
  {
    id: 55,
    title: "Taos Ski Valley, Taos, NM 87525",
    description: "🏂 Experience world-class snowboarding and adobe-style lodges at Taos Ski Valley in Taos, NM - a unique blend of adventure and culture! 🏔️❄️",
    position: [36.5965, -105.4487],
    category: "Entertainment",
  },
  {
    id: 56,
    title: "Gyeongbokgung Palace, Seoul, South Korea",
    description: "🏰 Explore the historic Gyeongbokgung Palace in Seoul, South Korea - a symbol of Korean royalty and architectural beauty! 🇰🇷",
    position: [37.5775, 126.9769],
    category: "International",
  },
  {
    id: 57,
    title: "Ha Long Bay, Quang Ninh Province, Vietnam",
    description: "⛵ Cruise through the breathtaking limestone karsts of Ha Long Bay in Vietnam - a UNESCO World Heritage Site and natural wonder! 🇻🇳",
    position: [20.9101, 107.1839],
    category: "International",
  },
  {
    id: 58,
    title: "Fushimi Inari Shrine, Kyoto, Japan",
    description: "⛩️ Wander through the iconic torii gates of Fushimi Inari Shrine in Kyoto, Japan - a sacred destination and cultural landmark! 🇯🇵",
    position: [34.9671, 135.7727],
    category: "International",
  },
  {
    id: 59,
    title: "The Great Wall of China, Huairou, China",
    description: "🏯 Experience the grandeur of The Great Wall of China in Huairou, China - an ancient marvel and testament to human engineering! 🇨🇳",
    position: [40.4319, 116.5704],
    category: "International",
  },
  {
    id: 60,
    title: "Myeongdong Street Food, Seoul, South Korea",
    description: "🍜 Indulge in a culinary adventure at Myeongdong Street Food in Seoul, South Korea - a vibrant market offering delicious Korean street eats! 🇰🇷🍢",
    position: [37.5665, 126.9850],
    category: "International",
  },
  {
    id: 61,
    title: "Hoi An Ancient Town, Quang Nam Province, Vietnam",
    description: "🏰 Step back in time at Hoi An Ancient Town in Vietnam - a charming destination with well-preserved architecture and cultural richness! 🇻🇳",
    position: [15.8801, 108.3380],
    category: "International",
  },
  {
    id: 62,
    title: "Tokyo Disneyland, Tokyo, Japan",
    description: "🎢 Embark on a magical journey at Tokyo Disneyland in Japan - a world of fantasy, enchantment, and beloved characters! 🇯🇵✨",
    position: [35.6329, 139.8808],
    category: "International",
  },
  {
    id: 63,
    title: "The Bund, Shanghai, China",
    description: "🌆 Marvel at the skyline along The Bund in Shanghai, China - a waterfront area showcasing a blend of historic and modern architecture! 🇨🇳",
    position: [31.2354, 121.4907],
    category: "International",
  },
  {
    id: 64,
    title: "Busan Gamcheon Culture Village, Busan, South Korea",
    description: "🏡 Immerse yourself in the colorful houses and artistic charm of Busan Gamcheon Culture Village in South Korea - a vibrant hillside community! 🇰🇷",
    position: [35.0989, 129.0367],
    category: "International",
  },
  {
    id: 65,
    title: "Sapa Terraces, Lao Cai Province, Vietnam",
    description: "🌾 Trek through the stunning terraced landscapes of Sapa in Vietnam - a scenic region known for its ethnic diversity and breathtaking views! 🇻🇳",
    position: [22.3368, 103.8447],
    category: "International",
  },
  {
    id: 66,
    title: "Arashiyama Bamboo Grove, Kyoto, Japan",
    description: "🎋 Stroll through the enchanting Arashiyama Bamboo Grove in Kyoto, Japan - a serene natural wonder and cultural treasure! 🇯🇵",
    position: [35.0154, 135.6739],
    category: "International",
  },
  {
    id: 67,
    title: "Zhangjiajie National Forest Park, Wulingyuan, China",
    description: "🌳 Discover the surreal beauty of Zhangjiajie National Forest Park in China - an otherworldly landscape that inspired the 'Avatar' movie! 🇨🇳",
    position: [29.3548, 110.4145],
    category: "International",
  },
  {
    id: 68,
    title: "Insadong, Seoul, South Korea",
    description: "🛍️ Shop for traditional crafts and savor authentic Korean tea in Insadong, Seoul - a cultural hub blending old and new! 🇰🇷☕",
    position: [37.5730, 126.9854],
    category: "International",
  },
  {
    id: 69,
    title: "Phong Nha-Ke Bang National Park, Quang Binh Province, Vietnam",
    description: "🏞️ Explore the stunning caves and karst landscapes of Phong Nha-Ke Bang National Park in Vietnam - a UNESCO World Heritage Site! 🇻🇳",
    position: [17.5902, 106.2830],
    category: "International",
  },
  {
    id: 70,
    title: "Tokyo Skytree, Tokyo, Japan",
    description: "🗼 Soar to new heights at Tokyo Skytree in Japan - the tallest structure in Tokyo offering panoramic views of the city! 🇯🇵🌆",
    position: [35.7101, 139.8107],
    category: "International",
  },
  {
    id: 71,
    title: "West Lake, Hangzhou, China",
    description: "🌸 Relax by the picturesque West Lake in Hangzhou, China - a scenic destination known for its natural beauty and cultural significance! 🇨🇳",
    position: [30.2466, 120.1439],
    category: "International",
  },
  {
    id: 72,
    title: "Jeju Loveland, Jeju Island, South Korea",
    description: "💏 Embark on an adventurous visit to Jeju Loveland on Jeju Island, South Korea - an art park featuring erotic sculptures and exhibits! 🇰🇷😘",
    position: [33.4977, 126.5292],
    category: "International",
  },
  {
    id: 73,
    title: "Mui Ne Sand Dunes, Binh Thuan Province, Vietnam",
    description: "🏜️ Experience the mesmerizing landscapes of Mui Ne Sand Dunes in Vietnam - a unique desert-like destination with red and white sand hills! 🇻🇳",
    position: [10.9695, 108.2847],
    category: "International",
  },
  {
    id: 74,
    title: "Meiji Shrine, Tokyo, Japan",
    description: "⛩️ Find tranquility at Meiji Shrine in Tokyo, Japan - a Shinto shrine surrounded by lush forest, offering a peaceful escape in the heart of the city! 🇯🇵🌳",
    position: [35.6764, 139.6993],
    category: "International",
  },
  {
    id: 75,
    title: "Yellow Mountain (Huangshan), Anhui Province, China",
    description: "🏞️ Marvel at the breathtaking scenery of Yellow Mountain (Huangshan) in China - a UNESCO World Heritage Site known for its iconic granite peaks and ancient pines! 🇨🇳",
    position: [30.1348, 118.1601],
    category: "International",
  },
  {
    id: 76,
    title: "Bukhansan National Park, Seoul, South Korea",
    description: "🏞️ Hike through the scenic trails of Bukhansan National Park in Seoul, South Korea - a nature escape offering panoramic views of the city! 🇰🇷🌲",
    position: [37.6580, 126.9810],
    category: "International",
  },
  {
    id: 77,
    title: "Cu Chi Tunnels, Ho Chi Minh City, Vietnam",
    description: "🕳️ Discover the historic Cu Chi Tunnels near Ho Chi Minh City, Vietnam - an underground network used during the Vietnam War! 🇻🇳",
    position: [11.0756, 106.5230],
    category: "International",
  },
  {
    id: 78,
    title: "Odaiba, Tokyo, Japan",
    description: "🏙️ Explore the futuristic entertainment hub of Odaiba in Tokyo, Japan - featuring shopping malls, digital art museums, and a life-sized Gundam statue! 🇯🇵🤖",
    position: [35.6190, 139.7798],
    category: "International",
  },
  {
    id: 79,
    title: "Hangzhou Tea Plantations, Hangzhou, China",
    description: "🍵 Immerse yourself in the lush greenery of Hangzhou Tea Plantations in China - a scenic destination renowned for its Longjing tea production! 🇨🇳🌿",
    position: [30.2861, 120.1439],
    category: "International",
  },
  {
    id: 80,
    title: "Namsan Seoul Tower, Seoul, South Korea",
    description: "🗼 Enjoy panoramic views of Seoul from Namsan Seoul Tower in South Korea - an iconic landmark and romantic spot in the city! 🇰🇷🌆",
    position: [37.5515, 126.9883],
    category: "International",
  },
  {
    id: 81,
    title: "Halong Bay Floating Fishing Village, Quang Ninh Province, Vietnam",
    description: "🚤 Cruise through the charming floating fishing villages of Halong Bay in Vietnam - a unique and tranquil experience! 🇻🇳",
    position: [20.9286, 107.1935],
    category: "International",
  },
  {
    id: 82,
    title: "Osaka Castle, Osaka, Japan",
    description: "🏯 Step into history at Osaka Castle in Osaka, Japan - a majestic fortress surrounded by beautiful cherry blossoms during springtime! 🇯🇵🌸",
    position: [34.6873, 135.5262],
    category: "International",
  },
  {
    id: 83,
    title: "Terracotta Army, Xi'an, China",
    description: "🗿 Marvel at the ancient Terracotta Army in Xi'an, China - an archaeological wonder featuring thousands of life-sized clay soldiers! 🇨🇳",
    position: [34.3840, 109.2793],
    category: "International",
  },
  {
    id: 84,
    title: "Eiffel Tower, Paris, France",
    description: "🗼 Soak in the iconic beauty of the Eiffel Tower in Paris, France - a symbol of romance and architectural elegance! 🇫🇷",
    position: [48.8588, 2.2944],
    category: "International",
  },
  {
    id: 85,
    title: "La Sagrada Familia, Barcelona, Spain",
    description: "⛪ Marvel at the masterpiece of Antoni Gaudí - La Sagrada Familia in Barcelona, Spain, a stunning basilica with unique architecture! 🇪🇸",
    position: [41.4036, 2.1744],
    category: "International",
  },
  {
    id: 86,
    title: "Stonehenge, Amesbury, U.K.",
    description: "🗿 Explore the mysterious Stonehenge in Amesbury, U.K. - an ancient and enigmatic prehistoric monument! 🇬🇧",
    position: [51.1789, -1.8262],
    category: "International",
  },
  {
    id: 87,
    title: "Louvre Museum, Paris, France",
    description: "🏛️ Dive into art and history at the Louvre Museum in Paris, France - home to thousands of masterpieces, including the Mona Lisa! 🇫🇷🎨",
    position: [48.8606, 2.3376],
    category: "International",
  },
  {
    id: 88,
    title: "Alhambra, Granada, Spain",
    description: "🕌 Immerse yourself in the Moorish architecture and gardens of Alhambra in Granada, Spain - a UNESCO World Heritage Site! 🇪🇸",
    position: [37.1773, -3.5986],
    category: "International",
  },
  {
    id: 89,
    title: "Edinburgh Castle, Edinburgh, U.K.",
    description: "🏰 Explore the historic Edinburgh Castle in Scotland, U.K. - a fortress with panoramic views and centuries of intriguing tales! 🇬🇧",
    position: [55.9486, -3.1999],
    category: "International",
  },
  {
    id: 90,
    title: "Mont Saint-Michel, Normandy, France",
    description: "⛪ Witness the magical island commune of Mont Saint-Michel in Normandy, France - an architectural marvel surrounded by the sea! 🇫🇷",
    position: [48.6367, -1.5113],
    category: "International",
  },
  {
    id: 91,
    title: "Park Güell, Barcelona, Spain",
    description: "🌳 Experience the whimsical world of Park Güell in Barcelona, Spain - a public park filled with colorful mosaics and playful architecture! 🇪🇸",
    position: [41.4145, 2.1527],
    category: "International",
  },
  {
    id: 92,
    title: "Buckingham Palace, London, U.K.",
    description: "🏰 Witness the grandeur of Buckingham Palace in London, U.K. - the official residence of the British monarch and a symbol of royalty! 🇬🇧",
    position: [51.5014, -0.1419],
    category: "International",
  },
  {
    id: 93,
    title: "Versailles Palace, Versailles, France",
    description: "🏰 Step into opulence at Versailles Palace near Paris, France - a symbol of absolute monarchy and French grandeur! 🇫🇷",
    position: [48.8049, 2.1204],
    category: "International",
  },
  {
    id: 94,
    title: "La Rambla, Barcelona, Spain",
    description: "🚶‍♀️ Stroll down the lively promenade of La Rambla in Barcelona, Spain - a bustling street filled with shops, cafes, and street performers! 🇪🇸",
    position: [41.3803, 2.1734],
    category: "International",
  },
  {
    id: 95,
    title: "Tower of London, London, U.K.",
    description: "🏰 Uncover centuries of history at the Tower of London in the U.K. - a fortress with a dark past and the Crown Jewels on display! 🇬🇧",
    position: [51.5081, -0.0759],
    category: "International",
  },
  {
    id: 96,
    title: "Provence Lavender Fields, Provence, France",
    description: "🌼 Immerse yourself in the vibrant colors of Provence Lavender Fields in France - a picturesque landscape during the blooming season! 🇫🇷",
    position: [43.9336, 5.6073],
    category: "International",
  },
  {
    id: 97,
    title: "La Pedrera (Casa Milà), Barcelona, Spain",
    description: "🏠 Admire the unconventional architecture of La Pedrera (Casa Milà) in Barcelona, Spain - a masterpiece by Antoni Gaudí! 🇪🇸",
    position: [41.3954, 2.1612],
    category: "International",
  },
  {
    id: 98,
    title: "Windsor Castle, Windsor, U.K.",
    description: "🏰 Visit the oldest and largest inhabited castle in the world - Windsor Castle in Windsor, U.K. - a royal residence with a rich history! 🇬🇧",
    position: [51.4839, -0.6044],
    category: "International",
  },
  {
    id: 99,
    title: "Palace of the Popes, Avignon, France",
    description: "🏰 Step into the historic Palace of the Popes in Avignon, France - a medieval palace that served as the residence for seven popes! 🇫🇷",
    position: [43.9506, 4.8072],
    category: "International",
  },
  {
    id: 100,
    title: "Plaza Mayor, Madrid, Spain",
    description: "🏛️ Immerse yourself in the grandeur of Plaza Mayor in Madrid, Spain - a historic square surrounded by vibrant architecture and lively atmosphere! 🇪🇸",
    position: [40.4154, -3.7074],
    category: "International",
  },
  {
    id: 101,
    title: "The Roman Baths, Bath, U.K.",
    description: "🏛️ Explore the ancient Roman Baths in the city of Bath, U.K. - a well-preserved complex with historical significance and stunning architecture! 🇬🇧",
    position: [51.3813, -2.3590],
    category: "International",
  },
  {
    id: 102,
    title: "Montparnasse Tower, Paris, France",
    description: "🏙️ Enjoy panoramic views of Paris from Montparnasse Tower in France - an observation deck offering breathtaking vistas of the cityscape! 🇫🇷🌆",
    position: [48.8418, 2.3216],
    category: "International",
  },
  {
    id: 103,
    title: "Sagrada Familia, Barcelona, Spain",
    description: "⛪ Marvel at the ongoing construction of Sagrada Familia in Barcelona, Spain - Antoni Gaudí's unfinished masterpiece and a UNESCO World Heritage Site! 🇪🇸",
    position: [41.4036, 2.1744],
    category: "International",
  },
  {
    id: 104,
    title: "Great Barrier Reef, Queensland, Australia",
    description: "🐠 Dive into the world's largest coral reef system, the Great Barrier Reef in Australia - a marine wonder teeming with biodiversity! 🇦🇺",
    position: [-18.2871, 147.6992],
    category: "International",
  },
  {
    id: 105,
    title: "Machu Picchu, Cusco Region, Peru",
    description: "🏞️ Embark on a journey to Machu Picchu in Peru - an ancient Incan citadel nestled in the Andes, surrounded by breathtaking landscapes! 🇵🇪",
    position: [-13.1631, -72.5450],
    category: "International",
  },
  {
    id: 106,
    title: "Petra, Ma'an Governorate, Jordan",
    description: "🏛️ Discover the rose-red city of Petra in Jordan - an archaeological marvel with intricate rock-cut architecture, including the iconic Al-Khazneh! 🇯🇴",
    position: [30.3285, 35.4444],
    category: "International",
  },
  {
    id: 107,
    title: "Grand Canyon, Arizona, USA",
    description: "🏜️ Marvel at the vastness of the Grand Canyon in the USA - a geological masterpiece with stunning rock formations and breathtaking canyon views! 🇺🇸",
    position: [36.1070, -112.1130],
    category: "International",
  },
  {
    id: 108,
    title: "Victoria Falls, Livingstone, Zambia/Zimbabwe",
    description: "🌊 Witness the awe-inspiring Victoria Falls on the border of Zambia and Zimbabwe - one of the world's largest and most majestic waterfalls! 🇿🇲🇿🇼",
    position: [-17.9244, 25.8567],
    category: "International",
  },
  {
    id: 109,
    title: "Santorini Sunset, Oia, Greece",
    description: "🌅 Experience the enchanting sunset in Oia, Santorini, Greece - a picturesque island offering breathtaking views over the Aegean Sea! 🇬🇷",
    position: [36.4614, 25.3760],
    category: "International",
  },
  {
    id: 110,
    title: "Bora Bora Overwater Bungalows, French Polynesia",
    description: "🏝️ Indulge in luxury at Bora Bora's overwater bungalows in French Polynesia - a tropical paradise with crystal-clear waters and stunning coral reefs! 🇵🇫",
    position: [-16.5000, -151.7500],
    category: "International",
  },
  {
    id: 111,
    title: "Northern Lights, Lapland, Finland",
    description: "🌌 Witness the magical Northern Lights in Lapland, Finland - a celestial display of vibrant colors dancing across the Arctic sky! 🇫🇮",
    position: [67.9222, 26.5046],
    category: "International",
  },
  {
    id: 112,
    title: "Amazon Rainforest, Brazil/Peru",
    description: "🌳 Explore the biodiversity of the Amazon Rainforest in Brazil and Peru - the world's largest tropical rainforest, home to diverse flora and fauna! 🇧🇷🇵🇪",
    position: [-3.4653, -62.2159],
    category: "International",
  },
  {
    id: 113,
    title: "Dubai Burj Khalifa, Dubai, UAE",
    description: "🏙️ Soar to new heights at the Burj Khalifa in Dubai, UAE - the world's tallest building, offering panoramic views of the city and beyond! 🇦🇪",
    position: [25.2769, 55.2962],
    category: "International",
  },
  {
    id: 114,
    title: "Serengeti Safari, Tanzania",
    description: "🦓 Embark on a Serengeti Safari in Tanzania - witness the Great Migration and experience the untamed beauty of African wildlife in their natural habitat! 🇹🇿",
    position: [-2.1540, 34.6857],
    category: "International",
  },
  {
    id: 115,
    title: "Neuschwanstein Castle, Bavaria, Germany",
    description: "🏰 Step into a fairy tale at Neuschwanstein Castle in Bavaria, Germany - an enchanting palace with stunning architecture and picturesque surroundings! 🇩🇪",
    position: [47.5576, 10.7498],
    category: "International",
  },
  {
    id: 116,
    title: "Angkor Wat, Siem Reap, Cambodia",
    description: "🕌 Discover the majestic Angkor Wat in Siem Reap, Cambodia - the largest religious monument in the world, surrounded by ancient ruins and temples! 🇰🇭",
    position: [13.4125, 103.8660],
    category: "International",
  },
  {
    id: 117,
    title: "Taj Mahal, Agra, India",
    description: "🕌 Marvel at the timeless beauty of the Taj Mahal in Agra, India - a symbol of eternal love and one of the most iconic landmarks in the world! 🇮🇳",
    position: [27.1750, 78.0419],
    category: "International",
  },
  {
    id: 118,
    title: "Iguazu Falls, Misiones Province, Argentina/Brazil",
    description: "🌊 Experience the power of Iguazu Falls on the border of Argentina and Brazil - a breathtaking series of waterfalls surrounded by lush rainforest! 🇦🇷🇧🇷",
    position: [-25.6953, -54.4368],
    category: "International",
  },
  {
    id: 119,
    title: "The Pyramids of Giza, Cairo, Egypt",
    description: "🏰 Explore the ancient wonders of the Pyramids of Giza in Cairo, Egypt - a testament to the grandeur of the ancient Egyptian civilization! 🇪🇬",
    position: [29.9792, 31.1342],
    category: "International",
  },
  {
    id: 120,
    title: "Banff National Park, Alberta, Canada",
    description: "🏞️ Immerse yourself in the stunning landscapes of Banff National Park in Alberta, Canada - a haven for outdoor enthusiasts with majestic mountains and turquoise lakes! 🇨🇦",
    position: [51.4968, -115.9281],
    category: "International",
  },
  {
    id: 121,
    title: "Acropolis, Athens, Greece",
    description: "🏛️ Climb to the Acropolis in Athens, Greece - an ancient citadel perched on a rocky outcrop, featuring iconic structures like the Parthenon! 🇬🇷",
    position: [37.9715, 23.7265],
    category: "International",
  },
  {
    id: 122,
    title: "Yellowstone National Park, Wyoming, USA",
    description: "🏞️ Explore the geothermal wonders of Yellowstone National Park in the USA - home to geysers, hot springs, and diverse wildlife in a pristine natural setting! 🇺🇸",
    position: [44.4279, -110.5885],
    category: "International",
  },
  {
    id: 123,
    title: "The Vatican City, Vatican City",
    description: "⛪ Visit the smallest independent state in the world - The Vatican City, a city-state surrounded by Rome, Italy, known for St. Peter's Basilica and the Sistine Chapel! 🇻🇦",
    position: [41.9022, 12.4538],
    category: "International",
  },

  {
    id: 124,
    title: "Antelope Canyon, Page, Arizona",
    description: "🏜️ Explore the mesmerizing slot canyons of Antelope Canyon in Page, Arizona - a surreal landscape of swirling sandstone formations! 🇺🇸",
    position: [36.8619, -111.3744],
    category: "Road Trip",
  },
  {
    id: 125,
    title: "Blue Ridge Parkway, North Carolina/Virginia",
    description: "🛣️ Drive along the scenic Blue Ridge Parkway, winding through the Appalachian Highlands - a road trip offering breathtaking views and outdoor adventures! 🇺🇸",
    position: [35.7815, -82.3882],
    category: "Road Trip",
  },
  {
    id: 126,
    title: "Denali National Park, Alaska",
    description: "🏞️ Experience the vast wilderness of Denali National Park in Alaska - home to North America's highest peak, Mount McKinley! 🇺🇸",
    position: [63.1148, -151.1926],
    category: "Road Trip",
  },
  {
    id: 127,
    title: "Great Smoky Mountains National Park, Tennessee/North Carolina",
    description: "🏞️ Discover the biodiversity and stunning landscapes of Great Smoky Mountains National Park - a haven for hikers, wildlife enthusiasts, and nature lovers! 🇺🇸",
    position: [35.6539, -83.5070],
    category: "Road Trip",
  },
  {
    id: 128,
    title: "Monument Valley, Utah/Arizona",
    description: "🏞️ Marvel at the iconic red mesas and buttes of Monument Valley on the Utah-Arizona border - a cinematic landscape featured in many Western films! 🇺🇸",
    position: [36.9982, -110.0985],
    category: "Road Trip",
  },
  {
    id: 129,
    title: "Napa Valley Wine Country, California",
    description: "🍇 Indulge in a wine-tasting adventure in Napa Valley, California - renowned for its vineyards, wineries, and picturesque countryside! 🇺🇸",
    position: [38.5025, -122.2654],
    category: "Road Trip",
  },
  {
    id: 130,
    title: "Horseshoe Bend, Page, Arizona",
    description: "🌊 Witness the stunning Horseshoe Bend along the Colorado River near Page, Arizona - a dramatic horseshoe-shaped meander with breathtaking canyon views! 🇺🇸",
    position: [36.8780, -111.5120],
    category: "Road Trip",
  },
  {
    id: 131,
    title: "Grand Tetons National Park, Wyoming",
    description: "🏞️ Explore the majestic peaks and pristine lakes of Grand Teton National Park in Wyoming - an outdoor paradise for adventure seekers! 🇺🇸",
    position: [43.7904, -110.6818],
    category: "Road Trip",
  },
  {
    id: 132,
    title: "New Orleans French Quarter, Louisiana",
    description: "🎺 Immerse yourself in the vibrant culture of the French Quarter in New Orleans, Louisiana - known for its lively music, historic architecture, and delicious cuisine! 🇺🇸",
    position: [29.9584, -90.0648],
    category: "Road Trip",
  },
  {
    id: 133,
    title: "Zion National Park, Utah",
    description: "🏞️ Embark on an adventure in Zion National Park, Utah - a red rock wonderland with towering sandstone cliffs and picturesque canyons! 🇺🇸",
    position: [37.2982, -113.0263],
    category: "Road Trip",
  },
  {
    id: 134,
    title: "Glacier National Park, Montana",
    description: "🏞️ Discover the pristine beauty of Glacier National Park in Montana - home to glaciers, alpine meadows, and stunning mountain landscapes! 🇺🇸",
    position: [48.7596, -113.7870],
    category: "Road Trip",
  },
  {
    id: 135,
    title: "Savannah Historic District, Georgia",
    description: "🏰 Stroll through the charming streets of the Savannah Historic District in Georgia - known for its cobblestone squares, historic homes, and southern hospitality! 🇺🇸",
    position: [32.0787, -81.0902],
    category: "Road Trip",
  },
  {
    id: 136,
    title: "Mount Rushmore National Memorial, South Dakota",
    description: "🏞️ Witness the iconic faces carved into Mount Rushmore in South Dakota - a patriotic monument featuring the likenesses of four U.S. presidents! 🇺🇸",
    position: [43.8789, -103.4590],
    category: "Road Trip",
  },
  {
    id: 137,
    title: "Yellowstone River, Montana/Wyoming",
    description: "🚣‍♂️ Float along the scenic Yellowstone River, flowing through Montana and Wyoming - an ideal spot for kayaking, fishing, and enjoying the great outdoors! 🇺🇸",
    position: [45.0945, -110.9646],
    category: "Road Trip",
  },
  {
    id: 138,
    title: "Cape Cod National Seashore, Massachusetts",
    description: "🏖️ Experience the natural beauty of Cape Cod National Seashore in Massachusetts - pristine beaches, dunes, and coastal landscapes along the Atlantic Ocean! 🇺🇸",
    position: [41.9375, -69.9721],
    category: "Road Trip",
  }

];

export default eventsData;
